#!/bin/bash
# PopFact Production Preparation Script
# Fixes critical issues for Chrome Web Store / Firefox Add-ons submission

set -e  # Exit on error

echo "🚀 PopFact Production Preparation"
echo "=================================="
echo ""

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

ERRORS=0
FIXED=0

# Check if ImageMagick is installed
if ! command -v convert &> /dev/null; then
    echo -e "${YELLOW}⚠️  ImageMagick not found${NC}"
    echo "Icons cannot be generated automatically."
    echo "Install ImageMagick:"
    echo "  - Ubuntu/Debian: sudo apt-get install imagemagick"
    echo "  - macOS: brew install imagemagick"
    echo "  - Or use online converter: https://cloudconvert.com/svg-to-png"
    echo ""
    MANUAL_ICONS=true
else
    MANUAL_ICONS=false
fi

echo "📋 Step 1: Generating PNG Icons"
echo "--------------------------------"

cd icons

if [ "$MANUAL_ICONS" = false ]; then
    # Generate all required icon sizes
    echo "Generating icons from icon.svg..."

    convert icon.svg -resize 16x16 icon16.png
    echo -e "  ${GREEN}✓${NC} icon16.png (16×16)"

    convert icon.svg -resize 32x32 icon32.png
    echo -e "  ${GREEN}✓${NC} icon32.png (32×32)"

    convert icon.svg -resize 48x48 icon48.png
    echo -e "  ${GREEN}✓${NC} icon48.png (48×48)"

    convert icon.svg -resize 96x96 icon96.png
    echo -e "  ${GREEN}✓${NC} icon96.png (96×96)"

    convert icon.svg -resize 128x128 icon128.png
    echo -e "  ${GREEN}✓${NC} icon128.png (128×128)"

    ((FIXED++))
else
    echo -e "${RED}❌ Skipped: ImageMagick not installed${NC}"
    echo "Manual action required: Generate PNG icons from icon.svg"
    ((ERRORS++))
fi

cd ..

echo ""
echo "📋 Step 2: Updating Manifest"
echo "--------------------------------"

# Backup original manifest
cp manifest.json manifest.json.backup

# Add missing fields using Python
python3 <<'EOF'
import json

with open('manifest.json', 'r') as f:
    manifest = json.load(f)

# Add recommended fields
manifest['short_name'] = 'PopFact'
manifest['homepage_url'] = 'https://github.com/PetrefiedThunder/PopFact'
manifest['author'] = 'PetrefiedThunder'

# Add 32 and 96 icons if they exist
manifest['icons']['32'] = 'icons/icon32.png'
manifest['icons']['96'] = 'icons/icon96.png'

# Update description to be more accurate
manifest['description'] = 'PopFact Demo - A proof-of-concept fact-checking overlay with CNN-style ticker. For demonstration purposes only.'

with open('manifest.json', 'w') as f:
    json.dump(manifest, f, indent=2)

print('✓ Added: short_name, homepage_url, author')
print('✓ Added: 32×32 and 96×96 icon references')
print('✓ Updated: description to reflect demo nature')
EOF

echo -e "${GREEN}✓${NC} Manifest updated"
((FIXED++))

echo ""
echo "📋 Step 3: Creating Disclaimer File"
echo "--------------------------------"

cat > DISCLAIMER.txt <<'DISCLAIMER'
POPFACT EXTENSION - IMPORTANT DISCLAIMER

This extension is a DEMONSTRATION/PROOF OF CONCEPT only.

WHAT THIS EXTENSION DOES:
- Displays a CNN-style news ticker at the bottom of web pages
- Extracts text content from pages
- Performs LOCAL keyword-based pattern matching
- Shows mock "fact-check" results in the ticker

WHAT THIS EXTENSION DOES NOT DO:
- Real fact-checking or verification
- Connect to actual fact-checking databases
- Provide accurate or reliable information
- Use AI or machine learning for analysis

THE FACT-CHECK RESULTS ARE GENERATED BY:
Simple keyword matching (e.g., "climate" → TRUE, "flat earth" → FALSE)
NOT by consulting authoritative sources or databases.

DO NOT RELY ON THIS EXTENSION FOR:
- Actual fact verification
- Important decisions
- Sharing as credible information
- Educational purposes requiring accuracy

INTENDED USE:
- Demonstration of browser extension development
- UI/UX concept for fact-checking overlays
- Learning tool for extension development
- Proof of concept for future development

For real fact-checking, please consult:
- Snopes.com
- FactCheck.org
- PolitiFact.com
- Reuters Fact Check
- AP Fact Check

By using this extension, you acknowledge that all results are
mock/demonstration data and should not be considered factual.

Version: 1.0.0
Last Updated: November 18, 2024
DISCLAIMER

echo -e "${GREEN}✓${NC} Disclaimer created"
((FIXED++))

echo ""
echo "📋 Step 4: Security Audit"
echo "--------------------------------"

echo "Checking for security issues..."

# Check for innerHTML usage
if grep -q "innerHTML" content.js; then
    echo -e "${YELLOW}⚠️  Warning: innerHTML found in content.js${NC}"
    echo "   Lines: $(grep -n "innerHTML" content.js | cut -d: -f1 | tr '\n' ',' | sed 's/,$//')"
    echo "   Recommendation: Replace with safer DOM methods"
    ((ERRORS++))
fi

# Check for eval usage
if grep -q "eval(" *.js; then
    echo -e "${RED}❌ Critical: eval() found${NC}"
    ((ERRORS++))
else
    echo -e "${GREEN}✓${NC} No eval() usage"
fi

# Check for external script loading
if grep -q "document.createElement('script')" *.js; then
    echo -e "${RED}❌ Warning: Dynamic script creation found${NC}"
    ((ERRORS++))
else
    echo -e "${GREEN}✓${NC} No dynamic script loading"
fi

echo ""
echo "📋 Step 5: Permissions Audit"
echo "--------------------------------"

if grep -q '"<all_urls>"' manifest.json; then
    echo -e "${YELLOW}⚠️  Broad permission: <all_urls>${NC}"
    echo "   This will trigger enhanced review"
    echo "   Users will see: 'Read and change all your data on all websites'"
    echo ""
    echo "   Consider alternatives:"
    echo "   - Use activeTab only (user grants per-site)"
    echo "   - Limit to specific domains"
    echo "   - Add justification in privacy policy"
else
    echo -e "${GREEN}✓${NC} Minimal permissions used"
fi

echo ""
echo "📋 Step 6: Creating Production Checklist"
echo "--------------------------------"

cat > PRODUCTION_CHECKLIST.md <<'CHECKLIST'
# PopFact Production Submission Checklist

## Pre-Submission (Complete Before Upload)

### Icons
- [ ] icon16.png exists and is valid PNG
- [ ] icon32.png exists (optional but recommended)
- [ ] icon48.png exists and is valid PNG
- [ ] icon96.png exists (optional but recommended)
- [ ] icon128.png exists and is valid PNG
- [ ] All icons have transparent backgrounds
- [ ] Icons are recognizable at all sizes

### Privacy Policy
- [ ] Privacy policy created
- [ ] Privacy policy hosted at public URL
- [ ] URL added to manifest (if required by store)
- [ ] Policy covers all data collection
- [ ] Policy explains permissions usage
- [ ] Policy includes contact information

### Documentation
- [ ] README.md is accurate and complete
- [ ] DISCLAIMER.txt is clear and prominent
- [ ] Description accurately reflects demo nature
- [ ] Screenshots prepared (1280×800 or 640×400)
- [ ] Promotional images created (if needed)

### Code Quality
- [ ] No console.log statements in production
- [ ] No TODO comments in production code
- [ ] Error handling for all async operations
- [ ] No hardcoded demo data (or clearly labeled)
- [ ] Code is well-commented

### Testing
- [ ] Tested on major websites (news sites)
- [ ] Tested on Chrome (latest version)
- [ ] Tested on Firefox (if submitting to AMO)
- [ ] No console errors on normal usage
- [ ] Extension can be cleanly uninstalled
- [ ] Settings persist correctly

### Security
- [ ] No innerHTML with user data
- [ ] No eval() usage
- [ ] No remote code execution
- [ ] All external resources bundled
- [ ] CSP defined (if applicable)

### Store Listing (Chrome Web Store)
- [ ] Detailed description (132+ characters)
- [ ] 5 screenshots (1280×800 or 640×400)
- [ ] Small promotional tile (440×280)
- [ ] Category selected
- [ ] Language specified
- [ ] Support email provided
- [ ] Privacy policy URL provided

### Store Listing (Firefox Add-ons)
- [ ] Add-on name (45 chars max)
- [ ] Summary (250 chars max)
- [ ] Description (detailed)
- [ ] Category selected
- [ ] Tags added (max 20)
- [ ] Support email/URL provided
- [ ] Privacy policy URL provided

### Legal
- [ ] License file present (Apache 2.0)
- [ ] Copyright notices correct
- [ ] No trademark violations
- [ ] Terms of service (if needed)

## Post-Submission

### Chrome Web Store
- [ ] Developer account created ($5 fee)
- [ ] Extension uploaded
- [ ] Store listing completed
- [ ] Privacy practices declared
- [ ] Preview listing before submit
- [ ] Submit for review
- [ ] Monitor review status

### Firefox Add-ons
- [ ] Developer account created (free)
- [ ] Extension uploaded
- [ ] Metadata completed
- [ ] Source code uploaded (if required)
- [ ] Submit for review
- [ ] Monitor review status

## Common Rejection Reasons

### Chrome Web Store:
- Missing privacy policy
- Misleading functionality description
- Security vulnerabilities (XSS, etc.)
- Excessive permissions without justification
- Broken functionality
- Violation of content policies

### Firefox Add-ons:
- Missing or inadequate privacy policy
- Unclear permission justifications
- Security issues
- Obfuscated code
- Violation of add-on policies

## Timeline Expectations

- Chrome Web Store: 1-7 days (longer with <all_urls>)
- Firefox Add-ons: 1-14 days (auto-review or manual)

## If Rejected

1. Read rejection reason carefully
2. Fix ALL issues mentioned
3. Update version number
4. Resubmit with explanation of changes
5. Be patient and professional in appeals

## Resources

- Chrome Developer Dashboard: https://chrome.google.com/webstore/devconsole
- Firefox Developer Hub: https://addons.mozilla.org/developers/
- Chrome Policies: https://developer.chrome.com/docs/webstore/program-policies/
- Firefox Policies: https://extensionworkshop.com/documentation/publish/add-on-policies/
CHECKLIST

echo -e "${GREEN}✓${NC} Production checklist created"
((FIXED++))

echo ""
echo "================================"
echo "📊 Preparation Summary"
echo "================================"

if [ $ERRORS -eq 0 ]; then
    echo -e "${GREEN}✅ $FIXED items fixed/created${NC}"
    echo ""
    echo "✅ NEXT STEPS:"
    echo "   1. Review PRODUCTION_CHECKLIST.md"
    echo "   2. Host PRIVACY_POLICY.md at public URL"
    echo "   3. Create store listing screenshots"
    echo "   4. Review PRODUCTION_AUDIT.md for remaining issues"
    echo "   5. Test extension thoroughly"
    echo "   6. Create developer account"
    echo "   7. Submit for review"
    echo ""
    echo "📁 Files created:"
    echo "   - icons/icon*.png (if ImageMagick available)"
    echo "   - DISCLAIMER.txt"
    echo "   - PRODUCTION_CHECKLIST.md"
    echo "   - manifest.json.backup (original backup)"
    echo ""
    echo "⚠️  REMAINING MANUAL TASKS:"
    echo "   - Host privacy policy at public URL"
    echo "   - Create screenshots (1280×800)"
    echo "   - Consider reducing <all_urls> permission"
    echo "   - Replace innerHTML with safer methods"
else
    echo -e "${YELLOW}⚠️  $FIXED items fixed/created, $ERRORS warnings${NC}"
    echo ""
    echo "❌ CRITICAL ISSUES:"
    if [ "$MANUAL_ICONS" = true ]; then
        echo "   - PNG icons need to be created manually"
    fi
    echo "   - Security warnings (innerHTML usage)"
    echo "   - Broad permissions may delay approval"
    echo ""
    echo "📋 See PRODUCTION_AUDIT.md for details"
fi

echo ""
echo "Preparation complete!"
